### ISSUE TITLE
Cannot create any form, after entering the name, it waits and does nothing

### ISSUE THREAD

**Issue by bulentevren** [quillforms/quillforms#103]
Here is the console info (I dont have any problem with rest API mydomain.com/wp-json shows output,

POST https://mydomain.com/wp-json/wp/v2/quill_forms?_locale=user 403
Uncaught (in promise) {code: 'rest_cannot_create', message: 'Sorry, you are not allowed to create posts as this user.', data: {…}}

**Comment by bulentevren** [comment]
admin.php:1 Uncaught (in promise) {code: 'rest_cannot_create', message: 'Sorry, you are not allowed to create posts as this user.', data: {…}}
Promise.then (async)
onClick @ index.js?ver=2b35eff69217208a5bc8:10
ha @ react-dom.min.js?ver=17.0.1:9
B @ react-dom.min.js?ver=17.0.1:9
(anonymous) @ react-dom.min.js?ver=17.0.1:9
He @ react-dom.min.js?ver=17.0.1:9
je @ react-dom.min.js?ver=17.0.1:9
(anonymous) @ react-dom.min.js?ver=17.0.1:9
sa @ react-dom.min.js?ver=17.0.1:9
(anonymous) @ react-dom.min.js?ver=17.0.1:9
Xe @ react-dom.min.js?ver=17.0.1:9
ge @ react-dom.min.js?ver=17.0.1:9
me @ react-dom.min.js?ver=17.0.1:9
unstable_runWithPriority @ react.min.js?ver=17.0.1:9
xn @ react-dom.min.js?ver=17.0.1:9
ua @ react-dom.min.js?ver=17.0.1:9
pe @ react-dom.min.js?ver=17.0.1:9

**Comment by mdmag** [comment]
@bulentevren 
This means the current user doesn't have admin permissions. Please make sure you have admin permission.

**Comment by bulentevren** [comment]
Yes, but there is only one admin account and I am using that account to create newnform :)

**Comment by mdmag** [comment]
@bulentevren,
So, it is clear that you should use this account to create forms.
