### ISSUE TITLE
Undefined constant 'QuillForms_Entries\Vendor\FALSE'

### ISSUE THREAD

**Issue by christianbayer** [quillforms/quillforms#108]
**Describe the bug**
When trying to run a `wp` command on CLI, the following error is thrown

```
Undefined constant 'QuillForms_Entries\Vendor\FALSE' in /home/DIR/wp-content/plugins/quillforms-entries/dependencies/build/vendor/mustangostang/spyc/Spyc.php:1251
```

Which leads to the following piece of code:

```
if (empty($_SERVER['PHP_SELF']) || \QuillForms_Entries\Vendor\FALSE === \strpos($_SERVER['PHP_SELF'], 'Spyc.php')) {
    break;
}
```

**To Reproduce**
1. Go to the WP root folder
2. Run any WP command, like `wp option get siteurl`

**Expected behavior**
No errors thrown.

**Plugin info:**
- QuillForms 2.1.0
- customthankyouscreenblock - 1.6.0
- entries - 3.0.0
- facebookpixel - 1.1.0
- googleanalytics - 1.1.0
- googlesheets - 1.5.0
- logic - 2.0.0
- opinionscaleblock - 1.2.0
- phoneblock - 1.2.1
- picturechoiceblock - 1.4.1
- ratingblock - 1.2.0
- signatureblock - 1.0.0
- webhooks - 1.0.1

**Server info:**
- Ubuntu 20.04
- PHP 7.4.33
- WordPress 6.1.1

**Comment by mdmag** [comment]
@christianbayer 
Thanks for reporting this issue.
We will release a new update to Entries addon that should fix this issue.

**Comment by mdmag** [comment]
Should have been fixed a few months ago.
