### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by Username-107** [quillforms/quillforms#115]
It would be really helpful to my application if someone could implement/help me implement some or all of these features:

- A way to allow the final submit button to be activated with the enter key (similar to all the "next" buttons)
- A way for the goToBlock function to be used outside of the onSubmit hook
- An option to switch the functions of ENTER and SHIFT+ENTER (ie. enter makes a new line and shift enter goes to the next block)
- An option for text entry boxes to be disabled (similar to the HTML attribute "disabled")

If any of this is obvious, please send me the documentation to solve it (I couldn't find it on GitHub or the website).

Thank you!

**Comment by Username-107** [comment]
Found information I needed at https://github.com/quillforms/quillforms/blob/master/react-docs/async-requests.md

**Comment by mdmag** [comment]
@Username-107 Glad that you were able to find your needed information
