### ISSUE TITLE
Autofocus into text

### ISSUE THREAD

**Issue by Username-107** [quillforms/quillforms#117]
I would like a way to autofocus into text blocks (similar to the HTML attribute autofocus).

**Comment by Username-107** [comment]
I realized that this only is not already the case for text blocks on the first slide. Can workaround my problem by adding a welcome screen. It might still be a useful addition in the future though.

**Comment by mdmag** [comment]
@Username-107 Can you please explain?
The short text question is getting auto focused programatically.
