### ISSUE TITLE
Typescripts errors

### ISSUE THREAD

**Issue by techiejd** [quillforms/quillforms#119]
**Describe the bug**

Missing types in react-renderer-utils. blocks could use a DisplayProps.

**To Reproduce**
`npm install --save @quillforms/react-renderer-utils`
Notice that there are no types there.

registerBlockType("name", {..., display: ({id,
    next,
    attributes,
    setIsValid,
    setIsAnswered,
    setValidationErr,
    showNextBtn,
    blockWithError,
    val,
    setVal,
    showErrMsg,}: any) => {})

**Expected behavior**

**Screenshots**
`npm install --save @quillforms/react-renderer-utils`
There are types there.

registerBlockType("name", {..., display: ({id,
    next,
    attributes,
    setIsValid,
    setIsAnswered,
    setValidationErr,
    showNextBtn,
    blockWithError,
    val,
    setVal,
    showErrMsg,}: DisplayProps) => {})

**Comment by mdmag** [comment]
Hi @techiejd,

Are you using the latest version of quillforms packages?

**Comment by felipesabino** [comment]
I just installed the latest version `@quillforms/react-renderer-utils@5.4.0` and I am facing the same error.

This is just a guess, but I think the `build-types` option is missing on [`react-renderer-utils` package.json](https://github.com/quillforms/quillforms/blob/master/packages/react-renderer-utils/package.json)

I could not dive deep on how the build setup works, but I noticed this directive in the other packages that I checked, including [`react-renderer-core` package.json](https://github.com/quillforms/quillforms/blob/master/packages/renderer-core/package.json#L23), which I am not seeing this error when I use the package in my project.

**Comment by mdmag** [comment]
@quillforms/react-renderer-utils package doesn't support Typescript yet. 
So you should use @ts-ignore before importing  registerCoreBlocks from this package.

**Comment by mdmag** [comment]
Closing this

**Comment by BB-BenBridges** [comment]
does @quillforms/react-renderer-utils support TS yet?
