### ISSUE TITLE
Enhancement: Implement more navigation features in Form API, and option to remove Quillforms navigation. 

### ISSUE THREAD

**Issue by ben-doyle** [quillforms/quillforms#120]
## Why
- The design is quite nice, copying type form very closely... nothing wrong with this.
- For those that might want to custom style the form outside the simple customCss inputs.

## What I have done:
- Created an [example](https://github.com/ben-doyle/quillforms-typescript-mui) that implements Material UI, and it's own navigation
  - Using simple CRA app.
  - All code implemented in TypeScript, including the example block from your docs.
  - A very simple block with MUI support, and navigation.
  - Just a visual example, the navigation implemented is `next()`, through a MUI button.
  
## Questions:
- Can we get `prev()`, `submit()` etc functions exposed in the Quillforms forms API?
- Can we get a setting such as `disableQuillformsNavigation` instead of my hack:
```css
/* Removes the Quillforms navigation */
.renderer-core-field-footer { display: none; }
```
- Let me know if you are open these changes, can help implement, thank you.

**Comment by mdmag** [comment]
Hello @ben-doyle,

For point number 2, We have already settings in the form object to help you achieve that.
Here is the form object type:
```js
type FormObj = {
	blocks: FormBlocks;
	themesList?: Theme[];
	theme?: Partial< FormTheme >;
	messages?: Partial< FormMessages >;
	logic?: FormLogic;
	settings?: {
		disableProgressBar?: boolean;
		disableWheelSwiping?: boolean;
		disableNavigationArrows?: boolean;
		animationDirection?: 'vertical' | 'horizontal';
		showQuestionsNumbers?: boolean;
		showLettersOnAnswers?: boolean;
	};
```

**Comment by antoniojlm84** [comment]
I have the same problem at point 1, prev(), submit() are very usefull but is not posible to handle this events,if you could provide them will be nice.

**Comment by animalillo** [comment]
I would like to trigger some actions on the event a user goes back as well, it would be neat to have this exposed!

**Comment by mdmag** [comment]
Hello @ben-doyle  @animalillo  @antoniojlm84 ,

Thanks for this feedback.
I have introduced a useful hook to expose the entire api for the renderer store.
Please view this [doc](https://github.com/quillforms/quillforms/blob/master/react-docs/use-renderer-store-actions.md) and let me know your feedback

**Comment by antoniojlm84** [comment]
Thanks @mdmag for your improvement and expose all these new functions. Everything works as expected.

But in my case I miss a beforeGoingPrev prop to take full control over the navigation of the form. 

Is there any hook or event  or way to control this event when I fire goPrev() or I click on the back arrow button/scroll up the wheel of mouse?

**Comment by mdmag** [comment]
Hello @animalillo, 
Please let me know your use case so I can guide you if possible?

**Comment by ansario** [comment]
@animalillo how does `goNext()` work with `beforeGoingNext`? `goNext()` appears to skip my validation logic.
