### ISSUE TITLE
How to use FormObj.hiddenFields?

### ISSUE THREAD

**Issue by felipesabino** [quillforms/quillforms#124]
**Describe the bug**
I am following the documentation and it does not mention the [`FormObj.hiddenFields`](https://github.com/quillforms/quillforms/blob/b2f8086ae5bae7ce9de4f601953375f504717afd/packages/renderer-core/src/types.ts#L29) property, which is not an optional argument

**To Reproduce**
1. Steps from documentation: https://github.com/quillforms/quillforms/blob/master/react-docs/get-started.md#getting-started
2. Also compilation error can be seen in the example sandbox the documentation provides: https://codesandbox.io/s/quill-forms-example-20uuf?file=/src/App.tsx

**Expected behavior**
1. The documentation and sandbox should be updated to contain this property and explain how it should be used
2. If not actually mandatory, the code should be updated to have it as optional and prevent compilation errors

**Screenshots**
![Screen Shot 2023-05-04 at 10 33 00 PM](https://user-images.githubusercontent.com/700480/236361758-eaf2b7dd-317d-4e29-a6a5-7bed429894d8.png)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by mdmag** [comment]
Hello @felipesabino,

Thanks for reporting this issue. 
I have just released a new version (5.3.1) for @quillforms/renderer-core 
Please update and this error should disappear.
Please let me know how it goes.

**Comment by mdmag** [comment]
Closing
