### ISSUE TITLE
Possible to manually update completed percentage?

### ISSUE THREAD

**Issue by jaredzwick** [quillforms/quillforms#127]
Hello, I am a huge fan of your work. I have just one usecase I have not yet been able to figure out.

So I am creating a form where users can upload files, once the file is submitted I use the next() to go to the next form, however the percent completed does not update.

Is this something I can update manually?

https://github.com/quillforms/quillforms/assets/52264361/0012ce37-0d22-49f1-9597-87d4fd018e8a

**Comment by mdmag** [comment]
Hello @jaredzwick,

You should use ```setIsAnswered(true)``` in your block.
```setIsAnswered``` is a prop sent to the display component.
