### ISSUE TITLE
UseCurrentBlock not found

### ISSUE THREAD

**Issue by alexiadltg** [quillforms/quillforms#128]
**Describe the bug**
Module '"@quillforms/renderer-core"' has no exported member 'useCurrentBlock'.ts(2305)

**To Reproduce**
import { useCurrentBlock } from "@quillforms/renderer-core";
const currentBlock = useCurrentBlock();

**Expected behavior**
to import useCurrentBlock successfully

**Desktop (please complete the following information):**
 - OS: arch linux
 - Browser: firefox
 - Version: 113.0.2

**Where I think its the bug** 

https://github.com/quillforms/quillforms/blob/master/packages/renderer-core/src/hooks/index.ts

I think the error its that useCurrentBlock its not exported

**Comment by mdmag** [comment]
@alexiadltg Should have been fixed now in latest version. Thanks for reporting this issue.
