### ISSUE TITLE
Feature request: auth protected forms 

### ISSUE THREAD

**Issue by Mourad-Ouerghi** [quillforms/quillforms#138]
We are using quillforms and we reached a deadend where our forms should be accessible to my authenticated users only is it possible to add it as a feature ?

**Comment by mdmag** [comment]
Are you talking about the WordPress version?
If so, we have the form locker addon in the plus plan which restricts the access to the logged in users only.

**Comment by Mourad-Ouerghi** [comment]
hello mohamed,
no i'm not talking the wordpress version we're looking to implement it in a
non wordpress website

Le mar. 15 août 2023 à 13:27, Mohamed Magdy ***@***.***> a
écrit :

**Comment by mdmag** [comment]
This can be done by custom code with React js .. Check if the user is authenticated and render the form in this case,
