### ISSUE TITLE
Add Beforegoingnext callback for each block

### ISSUE THREAD

**Issue by MoezGholami** [quillforms/quillforms#142]
The current implementation of beforegoingnext makes the entire form component to accept a Beforegoingnext. And in that, the user should select the component they want to add a functionality to.
It would be good if we could add Beforegoingnext for each form block instead of 1 for the entirety of the form.

**Comment by MoezGholami** [comment]
Honestly I came across this need by trying to use quillform in a way that it wasn't intended to; i.e: spliting up form data into multiple modules.
I still think having block specific `Beforegoingnext` is more intuitive though.
If you want to dismiss this issue, feel free to do so.

**Comment by mdmag** [comment]
I will rethink about that.
Closing for now
