### ISSUE TITLE
Unable to Unselect Multiple-Choice Option by Clicking Again

### ISSUE THREAD

**Issue by asad-amjad** [quillforms/quillforms#145]
**Issue Description**
After selecting an option in a multiple-choice question, it should be possible to unselect that option by clicking on it again. However, in the current implementation, once an option is selected, it cannot be unselected.

**To Reproduce**
1. Select an option in a multiple-choice question.
2. Attempt to unselect the same option by clicking on it again.
3. Observe that the option remains selected.

**Expected behavior**
The user should be able to unselect an option in a multiple-choice question by clicking on it again.

**Comment by mdmag** [comment]
Yeah, it was working before correctly.
I will fix this soon.

**Comment by mdmag** [comment]
@asad-amjad 
For WordPress plugin, this issue is fixed in version 3.2.3
For React, we released version 5.9.1 for react-renderer-utils package to fix this issue.
Thanks for reporting
