### ISSUE TITLE
how to change wording of page after submission?

### ISSUE THREAD

**Issue by abeatbeyondlab** [quillforms/quillforms#147]
I want to change this wording : 
```
Thanks for filling this in.
We will contact you soon
```

**Comment by mdmag** [comment]
WordPress version or React version?

**Comment by abeatbeyondlab** [comment]
react version

**Comment by abeatbeyondlab** [comment]
any info on this config issue ?

**Comment by mdmag** [comment]
Hello @abeatbeyondlab 

Sorry for being a bit late.
You can do that when you pass "messages" in your formObj prop.
The key that should be used is: block.defaultThankYouScreen.label
Pleae make sure you read [this doc](https://github.com/quillforms/quillforms/blob/master/react-docs/get-started.md) first.
