### ISSUE TITLE
Feature Request: Get pertial form filling analytics

### ISSUE THREAD

**Issue by DishantPal** [quillforms/quillforms#158]
Hi,

I wanted to know if there is any way I can get analytics on partially filled forms.

So what has been happening is that I have developed a form but people are not filling the form.

So I wanted to know if it's possible to know at which question or step people are dropping of. How many people are dropping of and such analytics. 

Would love to get these insights so that I can optimize my forms and improve conversion rates.

Looking forward to hear this.

Thank You.

**Comment by mdmag** [comment]
We already have this feature and we have already responded to this ticket via email
