### ISSUE TITLE
Feature Request: Posthog Analytics Integration

### ISSUE THREAD

**Issue by DishantPal** [quillforms/quillforms#159]
Hi, 

We are using Posthog for our analytics. 

Is there any integration available for that?

We have noticed that we have integration with Google Analytics and we are sending form inputs also by the user there.

Can we have something similar for Posthog as well?

I am looking forward to hearing back.

Thanks!

**Comment by mdmag** [comment]
We have responded to this ticket via email. Please don't copy paste the same support ticket in many places.
