### ISSUE TITLE
Multiple choice block isn't accessible via keyboard

### ISSUE THREAD

**Issue by mdmag** [quillforms/quillforms#16]
Multiple choice block has 2 problems:
1- when the user hit the choice key via keyboard, the corresponding choice doesn't get selected.
2- When the user hit "tab", it doesn't jump to the next choice, it jumps to the next block.

**Comment by robsonmafra** [comment]
@mdmag , I am validation here Quill Forms for accessibility and I am facing some issues with the multiple choice block. I found your issue here.
Have you found a solution for this one? I am starting to implement a custom multiple choice block that allows selection with keyboard and keys.

**Comment by ahmad-punch** [comment]
Multiple choice block has an annoying tooltip / hint labeled KEY when you hover over the choice, couldn't find anything in the documentation to stop that or hide that.

**Comment by mdmag** [comment]
@robsonmafra 
Fixed in last versions:
```
 "@quillforms/react-renderer-utils": "5.7.2",
 "@quillforms/renderer-core": "5.5.0"
```
@ahmad-punch 
We have now lettersOnAnswers boolean setting to disable this key.
