### ISSUE TITLE
How to run this as a react app

### ISSUE THREAD

**Issue by datduyng** [quillforms/quillforms#55]
**Describe the bug**
Hi, would you please provide example on how to run this as a react app
<img width="505" alt="CleanShot 2022-04-27 at 20 01 52@2x" src="https://user-images.githubusercontent.com/35666615/165650246-8d234277-9ee9-4170-a367-3345bbb734ab.png">

^^ is what I see when I run `yarn dev`

**Comment by crgone1** [comment]
Would love to know how to even get the code running?

**Comment by datduyng** [comment]
@crgone1  if you just got started with react app WP development then this is a very good video to get start https://www.youtube.com/watch?v=NKqogVcqDHA

**Comment by crgone1** [comment]
@datduyng Im building my first real project app entirely with Django and Mysql, but starting with SQlite DB first. I'm thinking of just building a simple typeform from scratch.

**Comment by crgone1** [comment]
@datduyng Actually decided to go with react js and Django rest framework.

**Comment by mdmag** [comment]
Hi guys,
I will share an example for using the form in a react app in a few days

**Comment by crgone1** [comment]
@mdmag Thank you so much. I would like to just know how to run the gui, build, modify and connect to react api. If my project is successful I will reach back out.

**Comment by mdmag** [comment]
Hi @datduyng @crgone1,
I did my best these days to support React community and to make sure that everything is working smoothly.
Finally, I am done but the full documentation will take time.
Please read [this page](https://github.com/quillforms/quillforms/blob/master/react-docs/installation.md) to know how to use the form in your react app.
At the bottom of this page, there is a Codesandbox example.
I will add more detailed documentation soon.
Please let me know how things are working.
Thanks!

**Comment by datduyng** [comment]
@mdmag  thank you so much :))

**Comment by mdmag** [comment]
@datduyng,
We have launched this application to support both WordPress community and React community as well. 
Do you think we should have another domain for React community that focuses on React only?
Currently quillforms.com is focusing on WordPress. 
Would it be a good idea to have another domain like quillforms.io or quillforms.org to focus on React, how to use the application and how to create custom blocks?

**Comment by datduyng** [comment]
@mdmag you should check out this twitter thread https://twitter.com/peer_rich/status/1521768994893701120 but I think your solution qualify to be a good OSS Typeform alternative and would bring lots of value

**Comment by datduyng** [comment]
@mdmag, Also, I am surprised that this repo only have 27 stars. You definitely deserve way more. Have you tried to launch thi s on producthunt?

**Comment by mdmag** [comment]
We had launched it on ProductHunt as a WordPress plugin: https://www.producthunt.com/posts/quill-forms
Not sure if they can enable us to launch another version for React community.

**Comment by datduyng** [comment]
You can try to create a subdomain i.e react.quillform.com or something

**Comment by mdmag** [comment]
I have added more detailed documentation and I replaced the page name. Please read [this page](https://github.com/quillforms/quillforms/blob/master/react-docs/get-started.md)
And thanks a lot for your advice.
