### ISSUE TITLE
Quillform on WP: GA/GTM tracking and thank you page

### ISSUE THREAD

**Issue by Mr-Jay** [quillforms/quillforms#57]
Hi, i am GA/GTM expert, and a customer asked me to track funnel of a form made with quillform. 

I usually use Google Tag Manager, but your product don't seems to give anything to track steps with it. 
Is there a way to generate a datalayer event for each step? 

For now i used the GA integration, but it seems we can connect only one property, my customer have GA-UA and GA4. 
How to connect both to the plugin? 

And last question, we need to track the form sent to confirme conversion with google ads, but with no datalayer event and no thank you page GTM can't know when conversion is confirmed. 
How to set up a redirection to a thank-you page automatically? 

Thank you.

**Comment by mdmag** [comment]
Hi @Mr-Jay,
Thanks for reaching out!

> For now i used the GA integration
Do you mean our GA integration in the Pro version? We have Google Analytics integration with our Pro version and it sends datalayer event after each step.

**Comment by Mr-Jay** [comment]
`Do you mean our GA integration in the Pro version? We have Google Analytics integration with our Pro version and it sends datalayer event after each step.`

I guess yes, i put the GA4 id and i indeed receive events. 

But as possible we would like to be able to manage event with GTM, and GTM don't seem to detect form's steps, and form submission. 

Step we can be ok to just use what GA intégration send, but for submission we really need to be able to track it with gtm to send conversion to different solutions.

**Comment by Mr-Jay** [comment]
My customer told me that he's already talking with you, and that you are currently working on the redirection, and to use shortcode instead of iframe. 

Those two things will be perfect to help to track with GTM, so i looking forward for this, it will be a great feature. 

Do you have a date frame for the release?

**Comment by mdmag** [comment]
By the end of this week, both features will be released!

**Comment by Mr-Jay** [comment]
Great news, thanks

**Comment by mdmag** [comment]
@Mr-Jay We have implemented the shortcode solution at the last version. Please update to the last version and update Google Analytics. Also, we have updated the custom thank you screen to have the auto-redirect feature.
Thanks!
