### ISSUE TITLE
Unintended comma character

### ISSUE THREAD

**Issue by imjlk** [quillforms/quillforms#59]
**Describe the bug**
[A clear and concise description of what the bug is.
](https://github.com/quillforms/quillforms/blob/3cfe22279b3ae45024f0009de95eb780149d13c7/packages/renderer-core/src/components/field-footer/index.tsx#L53)

https://github.com/quillforms/quillforms/blob/3cfe22279b3ae45024f0009de95eb780149d13c7/packages/renderer-core/src/components/field-footer/index.tsx#L53

**To Reproduce**
1. Go to [this line
](https://github.com/quillforms/quillforms/blob/3cfe22279b3ae45024f0009de95eb780149d13c7/packages/renderer-core/src/components/field-footer/index.tsx#L53
)
2. See error

**Expected behavior**
I think It must be deleted.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by mdmag** [comment]
@imjlk,
Thanks for this hint!
We fixed it in the last version we just published now!
Please check!
Thanks!
