### ISSUE TITLE
Jumping to submit after filling out required field

### ISSUE THREAD

**Issue by oliverrees** [quillforms/quillforms#60]
**Describe the bug**
Absolutely love the project. Thanks so much. 

One small bug — if a required answer is left blank, when the user clicks the submit button they are sent back to the unfilled field. When they fill in the required field they should be sent back to the submit button. Instead, they’re sent to the next (completed) question and then have to scroll through all their answers again to get to the submit page. This is OK if the form is only a few questions long but if you have 40+ question it takes a long time for the user to scroll through.

**To Reproduce**
1. Fill out a form but leave one required field blank
2. Press the submit button
3. You'll be scrolled back to the required field
4. Fill in the required field, and click OK
5. Instead of being scrolled back to the submit button, you'll be sent to the next (filled) question

**Expected behavior**
The user should be scrolled back to the submit button once they've filled in a missing required field

**Desktop (please complete the following information):**
All browers

**Smartphone (please complete the following information):**
All browers

**Additional context**
You can see the issue on https://quillforms.com/quillforms/support-form/ though it's not as annoying as the form isn't really long

**Comment by mdmag** [comment]
@oliverrees, 
Happy that you love the project. 
Thank you for mentioning this feature. When the user submit the form and if there are various invalid fields, we should let the form jump to the first invalid field then the next question should be the next invalid field if there is any other invalid field and if there isn't any other invalid field, we should jump to the last field.
Let me think about this. I think it is very doable easily. 
I will get back to you after implementing this feature.
Thanks!

**Comment by oliverrees** [comment]
@mdmag Amazing, thanks so much. Yes that's exactly the behaviour expected!

**Comment by mdmag** [comment]
Hi @oliverrees,
I have added this feature. 
Please update package: `@quillforms/renderer-core`  to version 1.5. 
Enjoy!

**Comment by mdmag** [comment]
If you need the WordPress version, we will update it probably today or tomorrow for this feature.

**Comment by oliverrees** [comment]
Thank you so much! 🙏

**Comment by mdmag** [comment]
@oliverrees,
Thanks a lot for your support!
