### ISSUE TITLE
Dynamic data rendering

### ISSUE THREAD

**Issue by oBLAZERo2001** [quillforms/quillforms#63]
**Dynamic data**
"  formObj={{  blocks: state, ...}} " 

on setState the data is not rendering on form.

///////////////

put blocks data in a state and update the state
the updated state value is not rendering in the form.

**Comment by mdmag** [comment]
@oBLAZERo2001 
Thanks for letting us know this issue.
We have upgraded @quillforms/renderer-core package to version 1.6.0 to fix this issue.
Please test and let us know how it goes now.

**Comment by oBLAZERo2001** [comment]
Great 🎉🎉🎉🎉🎉...
Issue fixed.

Thank you.😊

**Comment by denniemeijs** [comment]
Hi, i've tried rendering blocks based on state but it takes ages for the form to render the data, and it only does after an extra swipe. Furthermore once rendered it does not move back to the previous question anymore. Any thoughts?

**Comment by denniemeijs** [comment]
Not sure if my code is correct here but: https://codesandbox.io/s/g5rn54 

I am trying to add a question block based on the answer provided in the first question.
