### ISSUE TITLE
Can't run the project

### ISSUE THREAD

**Issue by VINCIDAO** [quillforms/quillforms#65]
**Describe the bug**
I am trying to install and run the quillforms on my local machine, but I can't

**To Reproduce**
1. Run npm i or Run npm ci

**Expected behavior**
Install all the dependencies and run the project

**Comment by VINCIDAO** [comment]
> Hi @VINCIDAO, We have a documentation to run the project as a React app. Please check: https://github.com/quillforms/quillforms/blob/master/react-docs/get-started.md

Hey!
I was asking for contribution and changes on the main project, not simply use it.

**Comment by mdmag** [comment]
Hey @VINCIDAO, 
Thanks for your interest for contribution.
You should do `npm run dev` after `npm install` and have the folder of the plugin inside `wp-content/plugins/`
You will notice then a new `build` folder has been created and this build folder contains the bundled script and assets of each package which we are using to enqueue inside WordPress.
Please let me know how it goes.
Thanks again!

**Comment by VINCIDAO** [comment]
When I try to run after the install I get the following
packages/navigation/src/index.ts:5:2 - error TS2305: Module '"react-router-dom"' has no exported member 'Switch'.

5  Switch,
   ~~~~~~

packages/navigation/src/index.ts:6:2 - error TS2305: Module '"react-router-dom"' has no exported member 'withRouter'.

6  withRouter,
   ~~~~~~~~~~

packages/navigation/src/index.ts:10:2 - error TS2305: Module '"react-router-dom"' has no exported member 'useRouteMatch'.

10  useRouteMatch,
    ~~~~~~~~~~~~~

packages/navigation/src/index.ts:11:2 - error TS2305: Module '"react-router-dom"' has no exported member 'Redirect'.

11  Redirect,

**Comment by mdmag** [comment]
You might have another version of `react-router-dom` locally or globally?

**Comment by mdmag** [comment]
Closing this due to no response
