### ISSUE TITLE
Is it okay to translate the text included in the packages?

### ISSUE THREAD

**Issue by imjlk** [quillforms/quillforms#67]
Hi, 

I'm not sure is this right way for translating packages files

For example, case of `packages/builder-core/src/components/no-blocks/index.tsx` file,

import `@wordpress/i18n` dependency like below
```
/**
 * WordPress Dependencies
 */
import { __ } from '@wordpress/i18n';
```

then can use translate function on this line,
https://github.com/quillforms/quillforms/blob/e8d29cdfaa0ad102e3fdb1acff97c649f15492bb/packages/builder-core/src/components/no-blocks/index.tsx#L123

like this
```
{ __( 'Please insert at lease one block.' ) }
```

And then, I think this project can make pot file with wp-cli like this
```
wp i18n make-pot . languages/quillforms.pot --ignore-domain
```
So generated `quillforms.pot` is contain of all translating text using __(), etc.

--- 
In the case of the gutenberg plugin, the text domain is not included when using the __() function inside of packages (like block package). Perhaps considering use outside of the WordPress context?

Please let me know if the above method is ok. I'm not sure because I don't have a good understanding of lerna.

**Comment by mdmag** [comment]
Yes, that should be correct. However we should add a text domain for us: "quillforms".
I am not sure you are asking for contributions or what? 
If so, you are very welcome to contribute.
We should have all text translated like you mentioned.

**Comment by imjlk** [comment]
Good, I think I could contribute. Thanks

**Comment by mdmag** [comment]
@imjlk, 
Cool, let me know if you need any help and thank you so much in advance for your contribution.

**Comment by mdmag** [comment]
Closing for now.
