### ISSUE TITLE
Compatible with React 18

### ISSUE THREAD

**Issue by alexiuscrow** [quillforms/quillforms#75]
Hi,

Can it be used with react 18 projects?

I tried and got the error:

> Error
> Invalid hook call. Hooks can only be called inside of the body of a function component. 

You can check my codesandbox fork here: https://codesandbox.io/s/quill-forms-example-typeform-clone-in-react-js-and-typescript-forked-301lcb

**Comment by mdmag** [comment]
Hi @alexiuscrow,

Thanks for reporting this.
This will take a few weeks to upgrade. Hopefully, soon.
I will ping you here after this upgrade.

**Comment by Lermatroid** [comment]
Any updates on React 18 support?

**Comment by samazadi** [comment]
Also waiting for this 🙏

**Comment by zned45** [comment]
+1

**Comment by mdmag** [comment]
React 18 will be supported by the end of this year.

**Comment by mdmag** [comment]
We will support React 18 by the end of this year.

**Comment by mdmag** [comment]
@alexiuscrow @samazadi @Lermatroid @zned45 
The project now supports React version 18!
Please update Quill Forms dependencies in your package.json to the last version.

**Comment by alexiuscrow** [comment]
@mdmag, thank you!
