### ISSUE TITLE
Use pangea dnd

### ISSUE THREAD

**Issue by Xhale1** [quillforms/quillforms#77]
Hello!

`react-beautiful-dnd` is no longer being maintained by Atlassian per their readme. It currently doesn't support React 18 and strict mode.

Another developer and myself created a fork [@hello-pangea/dnd](https://github.com/hello-pangea/dnd) which improves a few things:
- React 18 support
- React strict mode support
- React redux 8 support
- Converted entire codebase and tests to typescript
- Run test suite with React 16, 17, and 18

`@hello-pangea/dnd` is a drop-in replacement for `react-beautiful-dnd` and _should_ require no changes to support aside from renamed imports.

Would Quill Forms be interested in a PR adopting `@hello-pangea/dnd` instead of `react-beautiful-dnd`?

**Comment by mdmag** [comment]
@Xhale1, 
Thanks, we would be happy to have a PR to adopt `@hello-pangea/dnd` instead of `react-beautiful-dnd`

**Comment by mdmag** [comment]
Closing due to no feedback.
