### ISSUE TITLE
Can't use it in NextJS (Global CSS cannot be imported from within node_modules.)

### ISSUE THREAD

**Issue by TheHoltz** [quillforms/quillforms#82]
**Describe the bug**
When using the package in a NextJS project, it complains that a Global CSS cannot be imported from within node_modules.

**To Reproduce**
1. Start a fresh NextJS Project
2. Install the library
3. Import the library

**Expected behavior**
Here is a explanation from NextJS in how to fix it: https://nextjs.org/docs/messages/css-npm

**Screenshots**
![Captura de Tela 2022-09-09 às 17 55 56](https://user-images.githubusercontent.com/38303017/189443676-5d7b8422-a884-48fa-aa1f-798ca7be7fe8.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome

**Comment by mdmag** [comment]
Hi @TheHoltz,
Thanks for reporting this issue.
I will check that and we will have an update to fix this issue.

**Comment by mbashiq** [comment]
Facing this issue for me as well

**Comment by Lermatroid** [comment]
Hey @TheHoltz, did you wind up finding a solution to this issue?

**Comment by mdmag** [comment]
@Lermatroid @mbashiq @TheHoltz, 
We are working on an update for this. You can expect this issue will be resolved within a week from today.

**Comment by Lermatroid** [comment]
Awesome, thanks @mdmag!

**Comment by Lermatroid** [comment]
Hey @mdmag, any updates on this? Thanks!

**Comment by safwanyp** [comment]
Any updates on this? Been having this issue for a while and it's really slowing down production.

**Comment by wqawasmi** [comment]
Issue still persists, it's blocking me from integrating this into a project.

**Comment by mdmag** [comment]
@safwanyp @wqawasmi @mbashiq @TheHoltz @Lermatroid 
Ok guys, I am so sorry for being late.
Final promise, we will support Next Js by This Monday.
Thanks for your patience.

**Comment by mdmag** [comment]
I fixed the issue.
Going to have a newer release within a few hours.

**Comment by DovAzencot** [comment]
Getting the same issue as @wqawasmi

**Comment by mdmag** [comment]
@wqawasmi 
Thanks for reporting this issue,
I spent more than 8 hours investigating this issue and I fixed many problems and it seems that I am 99% done but there is still one more error I will try to solve it after having some rest.

**Comment by wqawasmi** [comment]
@mdmag Appreciate you putting in all this effort in resolving the problem :) You're the best!

**Comment by mdmag** [comment]
I fixed all issues related to Quill Forms itself but there is a problem with a dependency we use in our project.
I contacted the developers of this dependency and I will make a pull request to fix their issue and hope they would release a new version soon.

**Comment by mdmag** [comment]
@wqawasmi 
Good news.
I have managed to get this fixed and I have tested it. 
Please note that we don't support React 18 yet but we will support it soon. 
This is my package.json 
` "dependencies": {
    "@quillforms/react-renderer-utils": "^2.5.0",
    "@quillforms/renderer-core": "^2.6.0",
    "next": "12.1.2",
    "react": "17.0.2",
    "react-dom": "17.0.2"
  },`
  
  Please let me know if it works now!

**Comment by mdmag** [comment]
@wqawasmi @mbashiq @safwanyp @TheHoltz @Lermatroid @DovAzencot  @Christobill 
Can any one please confirm that this issue has been resolved?

**Comment by muhamed-didovic** [comment]
Hi @mdmag, 

Does this work with next.js version 13 and react version 18?
I think one example in codesandbox or similar would resolve a lot of issues and how to use it.

**Comment by mdmag** [comment]
Hey @muhamed-didovic,

Thanks for reporting this bug.
I have released version 5.2.0 to fix bugs with NextJS

**Comment by muhamed-didovic** [comment]
thanks @mdmag, it works
