### ISSUE TITLE
Compatibility with React Native

### ISSUE THREAD

**Issue by shruti222patel** [quillforms/quillforms#83]
Hi All, is there any plans to adapt this for a React Native implementation?

**Comment by mdmag** [comment]
Hi @shruti222patel,
I am not very familiar with React Native. Not sure how we should make the code compatible with React Native as well. Do you have any guide?

**Comment by shruti222patel** [comment]
It seems the logic can be reused, but the, but the presentation code will most likely have to be updated using the React Native components: https://facebook.github.io/react-native/docs/getting-started.html. 


Disclaimer: I have limited experience with react in general (native and web).

**Comment by mdmag** [comment]
We will consider supporting React native later.
I will close this issue for now and I will ping you here once we add the support for React Native.

Thanks!

**Comment by 0xmtn** [comment]
Hey @mdmag ,

Is there a plan on supporting React-native?
