### ISSUE TITLE
Support RTL

### ISSUE THREAD

**Issue by mdmag** [quillforms/quillforms#9]
The form renderer doesn't fully support RTL.

**Comment by yglik** [comment]
Is there a support for RTL?
if not, how can I contribute?

**Comment by mdmag** [comment]
@yglik 
It works with RTL now. 
This issue should be closed.
Instead of this line:
`import "@quillforms/renderer-core/build-style/style.css";`
You should use this:
`import "@quillforms/renderer-core/build-style/style-rtl.css";`

**Comment by yglik** [comment]
Awesome, 
Thank you very much!

**Comment by yglik** [comment]
Hey, I’m searching for the place to import style-rte.css and I can’t find it
I am currently using the free version to check if Quillforms will be good for my site, if it is, I will buy the pro version.

Ca you please help me implement the RTL style?
Where should I use this :
***@***.***/renderer-core/build-style/style-rtl.css”?
