### ISSUE TITLE
Support images in multiple choice and text field – Enhancement 

### ISSUE THREAD

**Issue by sebabelmar** [quillforms/quillforms#97]
Typeform support images and open text field (other) in multiple-choice blocks.
After looking at the implementation it should be relatively easy to add.

Happy to contribute to the project to avoid having to fork or create a custom block just for that.

LMK if I can help or if this is on the road map at all.

Thanks.

**Comment by mdmag** [comment]
We have already a picture choice block in a private repo. I will think about moving it to the public repo. 
Your contribution will be of course welcomed for having the text field with (other) in multiple choice block.

**Comment by mdmag** [comment]
@sebabelmar We have implemented an example for picture choice block: 
https://codesandbox.io/s/quill-forms-picture-choice-question-gxlmqy

**Comment by natcohen** [comment]
@mdmag If you open a bounty for that, I am willing to [financially contribute](https://oss.issuehunt.io/) for the "other" open ended answer; if the price is reasonable...
